ARGS localhost encoder 1 /home/gaoziyuan/project/bamboo/project_pactum/external/deepspeed/DeepSpeedExamples/pipeline_parallelism/transformer
RUNNING CMD export PROJECT_PACTUM_LOGGING_WARNING='etcd.client,etcd.lock,torch.distributed.distributed_c10d' 	export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python 	&& 	export PYTHONPATH=/home/gaoziyuan/project/bamboo/project-pactum:${PYTHONPATH} 	&& 	python -m project_pactum.run 	--rdzv_backend=etcd-v2 	--rdzv_endpoint=localhost:2379 	--rdzv_id=encoder 	--nnodes=1:64 	--nproc_per_node=1 	--project-pactum 	--max-pipe-parallel-size=24 	--default-num-stages=1 	/home/gaoziyuan/project/bamboo/project_pactum/external/deepspeed/DeepSpeedExamples/pipeline_parallelism/transformer.py 	--backend=nccl 	--redundancy_level=1 	 	--deepspeed 	--deepspeed_config /home/gaoziyuan/project/bamboo/project_pactum/external/deepspeed/DeepSpeedExamples/pipeline_parallelism/transformer.json
[1;36m[0.044 p54259/t140606186587968 INFO root][m [36mUsing nproc_per_node=1.[m
[1;33m[0.044 p54259/t140606186587968 WARNING project_pactum.etcd][m [33mStart create_rdzv_handler[m
WARNING 2024-03-01 16:44:08,309 Etcd machines: ['http://localhost:2379', 'http://localhost:4001']
[1;33m[0.062 p54259/t140606186587968 WARNING project_pactum.etcd][m [33mEnd create_rdzv_handler[m
[1;33m[0.096 p54259/t140601353721600 WARNING project_pactum.agent.api][m [33m1709282648.3569632, 0.908393431204004, ready ? False[m
WARNING 2024-03-01 16:44:08,357 Attempting to join next rendezvous
[1;33m[0.096 p54259/t140606186587968 WARNING project_pactum.etcd][m [33m/torchelastic/p2p/run_encoder/rdzv/active_version[m
WARNING 2024-03-01 16:44:08,364 New rendezvous state created: {'status': 'joinable', 'version': '1', 'participants': []}
WARNING 2024-03-01 16:44:08,452 Joined rendezvous version 1 as rank 0. Full state: {'status': 'joinable', 'version': '1', 'participants': [0]}
WARNING 2024-03-01 16:44:08,452 Rank 0 is responsible for join last call.
[1;33m[3.099 p54259/t140601353721600 WARNING project_pactum.agent.api][m [33m1709282651.3605103, 0.6555078456820653, ready ? False[m
WARNING 2024-03-01 16:44:13,471 Rank 0 finished join last call.
WARNING 2024-03-01 16:44:13,471 Waiting for remaining peers.
WARNING 2024-03-01 16:44:13,473 All peers arrived. Confirming membership.
[1;33m[5.303 p54259/t140606186587968 WARNING project_pactum.etcd][m [33mnum_active_nodes: 1[m
[1;33m[5.303 p54259/t140606186587968 WARNING project_pactum.etcd][m [33mnum_participants: 1[m
WARNING 2024-03-01 16:44:13,571 Waiting for confirmations from all peers.
WARNING 2024-03-01 16:44:13,572 Rendezvous version 1 is complete. Final state: {'status': 'final', 'version': '1', 'participants': [0], 'keep_alives': ['/torchelastic/p2p/run_encoder/rdzv/v_1/rank_0'], 'num_workers_waiting': 0, 'previous_version': '-1', 'num_pipelines': '1', 'num_stages': '1'}
WARNING 2024-03-01 16:44:13,577 Creating EtcdStore as the c10d::Store implementation
[1;33m[6.103 p54259/t140601353721600 WARNING project_pactum.agent.api][m [33m1709282654.363968, 0.23195382260109054, ready ? True[m
[1;33m[6.103 p54259/t140601353721600 WARNING project_pactum.agent.api][m [33m1709282654.3647246, 0.23195382260109054, Preemption detected[m
[1;33m[6.104 p54259/t140606186587968 WARNING project_pactum.agent.api][m [33mDraining worker pid=54386 due to preemption[m
[1;31m[10.350 p54259/t140606186587968 ERROR torch.distributed.elastic.multiprocessing.api][m [31mfailed (exitcode: -15) local_rank: 0 (pid: 54386) of binary: /home/gaoziyuan/miniconda3/envs/Bamboo/bin/python[m
[1;31m[10.350 p54259/t140606186587968 ERROR project_pactum.agent.api][m [31m[default] Worker group failed[m
Traceback (most recent call last):
  File "/home/gaoziyuan/miniconda3/envs/Bamboo/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/gaoziyuan/miniconda3/envs/Bamboo/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/gaoziyuan/project/bamboo/project_pactum/run/__main__.py", line 5, in <module>
    project_pactum.run.main(sys.argv[1:])
  File "/home/gaoziyuan/project/bamboo/project_pactum/run/__init__.py", line 246, in main
    run(options)
  File "/home/gaoziyuan/project/bamboo/project_pactum/run/__init__.py", line 240, in run
    )(*cmd_args)
  File "/home/gaoziyuan/project/bamboo/project_pactum/run/api.py", line 107, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/gaoziyuan/miniconda3/envs/Bamboo/lib/python3.7/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/gaoziyuan/project/bamboo/project_pactum/run/api.py", line 371, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home/gaoziyuan/project/bamboo/project_pactum/external/deepspeed/DeepSpeedExamples/pipeline_parallelism/transformer.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-03-01_16:44:18
  host      : zkyd
  rank      : 0 (local_rank: 0)
  exitcode  : -15 (pid: 54386)
  error_file: <N/A>
  traceback : Signal 15 (SIGTERM) received by PID 54386
============================================================
http://localhost:2379/v2/machines
http://localhost:2379/v2/machines
